name: Terraform apply

on:
  push:
    branches: ['main']
    # paths: 
    #   - deployment/

permissions: 
  id-token: write
  contents: read  

env:
  AWS_REGION: eu-west-2


jobs:   
  apply:
    runs-on: ubuntu-24.04

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials w/ OIDC
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::174350032095:role/eks-admin
            aws-region: ${{ env.AWS_REGION }}

        - name: Terraform apply
          uses: dflook/terraform-apply@v2
          with:
            path: Terraform
            auto_approve: true


